name: chamasoft
description: The new Chamasoft app
version: 2.0.3+88

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.0-dev.2"
  firebase_messaging: "^7.0.0-dev.1"
  #firebase_crashlytics: "^0.2.0-dev.5"
  flutter_vector_icons: ^0.2.1
  line_awesome_icons: ^1.0.4+2
  introduction_screen: ^1.0.8
  http: ^0.12.1
  launch_review: ^2.0.0
  provider: ^4.0.4
  url_launcher: ^5.6.0
  pin_input_text_field: ^3.0.1
  md2_tab_indicator: ^1.0.2
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  contacts_service: ^0.4.6
  permission_handler: ^5.0.0+hotfix.4
  fl_chart: ^0.9.4
  package_info: ^0.4.0+16
  encrypt: ^4.0.1
  tuple: ^1.0.3
  cached_network_image: ^2.2.0+1
  country_code_picker: ^1.4.0
  libphonenumber: ^1.0.1
  shimmer: ^1.1.1
  flutter_svg: ^0.18.0
  image_picker: ^0.6.7+9
  sms_autofill: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/main.png"

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/tiles/
   - assets/certificates/mpesachama.crt
   - assets/certificates/mobile.key
   - assets/certificates/pubkey.pem
  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeuisl.ttf
          weight: 300
        - asset: assets/fonts/segoeui.ttf
          weight: 400
        - asset: assets/fonts/seguisb.ttf
          weight: 600
        - asset: assets/fonts/segoeuib.ttf
          weight: 700