name: chamasoft
description: The new Chamasoft app
version: 1.0.0+74

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vector_icons: ^0.2.1
  line_awesome_icons: ^1.0.4+2
  introduction_screen: ^1.0.8
  http: ^0.12.0+4
  launch_review: ^2.0.0
  cached_network_image: ^2.0.0
  firebase_crashlytics: ^0.1.3
  provider: ^4.0.4
  url_launcher: ^5.4.1
  pin_input_text_field: ^3.0.1
  md2_tab_indicator: ^1.0.2
  shared_preferences: ^0.5.6+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/main.png"

flutter:
  uses-material-design: true

  assets:
   - assets/
  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/segoeuii.ttf
          style: italic
        - asset: assets/fonts/segoeuib.ttf
          weight: 700
        - asset: assets/fonts/segoeuiz.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/segoeuil.ttf
          weight: 200
        - asset: assets/fonts/seguili.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/segoeuisl.ttf
          weight: 300
        - asset: assets/fonts/seguisli.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/seguisb.ttf
          weight: 600
        - asset: assets/fonts/seguisbi.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/seguibl.ttf
          weight: 900
        - asset: assets/fonts/seguibli.ttf
          weight: 900
          style: italic