name: chamasoft
description: The new Chamasoft app
version: 2.2.7+234

environment:
  sdk: '>=2.2.2 <=3.0.0'

# flutter: '2.0.3'
dependencies:
  flutter:
    sdk: flutter
  flutter_vector_icons: ^2.0.0
  line_awesome_flutter: ^2.0.0
  introduction_screen: ^3.1.6
  http: ^0.13.5
#  launch_review: ^3.0.1
  provider: ^6.0.5
  url_launcher: ^6.1.10
  pin_input_text_field: ^4.5.0
  # md2_tab_indicator: ^1.0.2
  shared_preferences: ^2.0.18
  intl: 0.17.0
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  fl_chart: ^0.61.0
  # package_info: ^2.0.2
  package_info_plus: ^3.0.3
  encrypt: ^5.0.1
#  tuple: ^2.0.1
  cached_network_image: ^3.2.3
  country_code_picker: ^3.0.0
  libphonenumber: ^2.0.2
  shimmer: ^2.0.0
  flutter_svg: ^2.0.3
  image_picker: ^0.8.7
  sms_autofill: ^2.3.0
  sqflite: ^2.2.5
  date_time_picker: ^2.1.0
  flutter_share_me: ^1.4.0
#  dropdown_formfield: ^0.1.4
  flutter_form_builder: ^7.8.0
  firebase_messaging: ^14.6.6
  firebase_core: ^2.15.1
  flutter_local_notifications: ^15.1.0+1
#  modal_bottom_sheet: ^2.1.2
  loader_overlay: ^2.1.0
  fluttertoast: ^8.2.1
#  lite_rolling_switch: ^1.0.0
  flutter_toggle_tab: ^1.2.0
#  back_button_interceptor: ^6.0.2
#  grouped_list: ^5.1.2
  crisp: ^0.3.1

  # share: ^0.6.5+4
#  share_plus: any

  screenshot: ^1.3.0
  share_plus: ^6.3.1
  image_gallery_saver: ^2.0.3
  pdf: 3.9.0
  path_provider: ^2.0.13

  # open_file: ^lastVersion 

  dotted_line: ^3.1.0
#  data_table_2: ^2.4.1

  webview_flutter: ^3.0.0
  showcaseview: ^2.0.2
  loading_overlay: ^0.3.0
#  in_app_review: ^2.0.6
  rate_my_app: ^1.1.4
  # # contact_picker: any
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  tab_indicator_styler: ^2.0.0
  flutter_pdfview: ^1.2.5
  pie_chart: ^5.3.2
  get: 4.6.5
  line_icons: ^2.0.3

dependency_overrides:
  firebase_messaging_platform_interface: 4.2.15
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  dependency_validator: ^3.0.0
  dart_code_metrics: ^5.7.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/main.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tiles/
    - assets/certificates/mpesachama.crt
    - assets/certificates/mobile.key
    - assets/certificates/pubkey.pem
    - assets/icon/main.png
  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeuisl.ttf
          weight: 300
        - asset: assets/fonts/segoeui.ttf
          weight: 400
        - asset: assets/fonts/seguisb.ttf
          weight: 600
        - asset: assets/fonts/segoeuib.ttf
          weight: 700