name: chamasoft
description: The new Chamasoft app
version: 2.1.1+92

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vector_icons: ^0.2.1
  line_awesome_icons: ^1.0.4+2
  introduction_screen: ^1.0.8
  http: ^0.13.3
  launch_review: ^2.0.0
  provider: ^4.0.4
  url_launcher: ^6.0.4
  pin_input_text_field: ^3.3.1
  md2_tab_indicator: ^1.0.2
  shared_preferences: ^2.0.5
  intl: ^0.16.1
  contacts_service: ^0.4.6
  permission_handler: ^8.0.0+2
  fl_chart: ^0.12.3
  package_info: ^0.4.0+16
  encrypt: ^4.1.0
  tuple: ^1.0.3
  cached_network_image: ^2.2.0+1
  country_code_picker: ^1.4.0
  libphonenumber: ^2.0.0
  shimmer: ^1.1.1
  flutter_svg: ^0.19.3
  image_picker: ^0.7.5+3
  sms_autofill: ^1.2.7
  sqflite: ^1.3.0
  date_time_picker: "^1.1.1"
  flutter_share_me: ^0.9.1
  dropdown_formfield: ^0.1.3
  firebase_messaging: ^10.0.0
  firebase_core: ^1.2.0
  flutter_local_notifications: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/main.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tiles/
    - assets/certificates/mpesachama.crt
    - assets/certificates/mobile.key
    - assets/certificates/pubkey.pem
  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeuisl.ttf
          weight: 300
        - asset: assets/fonts/segoeui.ttf
          weight: 400
        - asset: assets/fonts/seguisb.ttf
          weight: 600
        - asset: assets/fonts/segoeuib.ttf
          weight: 700
