
Map<String, String> customIcons = {
  "no-data": "assets/no-data.svg",
  "wallet": "assets/tiles/wallet.svg",
  "invoice": "assets/tiles/invoice.svg",
  "expense": "assets/tiles/purchase.svg",
  "transaction": "assets/tiles/transaction.svg",
  "account": "assets/tiles/account.svg",
  "bank": "assets/tiles/bank.svg",
  "bank-cards": "assets/tiles/bank-cards.svg",
  "blockchain": "assets/tiles/blockchain.svg",
  "card-payment": "assets/tiles/card-payment.svg",
  "cash-in-hand": "assets/tiles/cash-in-hand.svg",
  "cash-register": "assets/tiles/cash-register.svg",
  "female": "assets/tiles/check-female.svg",
  "couple": "assets/tiles/couple-icloud.svg",
  "gears": "assets/tiles/gears.svg",
  "group": "assets/tiles/group.svg",
  "user-female": "assets/tiles/lock-female-user.svg",
  "user-male": "assets/tiles/lock-male-user.svg",
  "money-bag": "assets/tiles/money-bag.svg",
  "refund": "assets/tiles/refund.svg",
  "safe": "assets/tiles/safe.svg",
  "account-male": "assets/tiles/see-male-account.svg",
  "verified-account": "assets/tiles/verified-account.svg",
};